name: wonderland
favicon: null
layout_spectrum: 0.5527971496339887
typography_spectrum: 0.1628075756598264
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.36434770259074867
  lightness: 0.9887264030985534
  saturation: 0.7895294304471463
  rhythmicContrast: 0.32236274029128253
purpose: []
