name: wonderland
favicon: null
layout_spectrum: 0.64158
typography_spectrum: 0.1628075756598264
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6f4f2'
    - '#361112'
    - '#7f7d71'
    - '#bd3636'
    - '#c3bdaa'
  brandStrength: 0.4375
  lightness: 0.9887264030985534
  saturation: 0.7895294304471463
  rhythmicContrast: 0.5
purpose: []
